### ISSUE TITLE
keine alt und title Tag bei Bildern

### ISSUE THREAD

**Issue by thuer-it** [ErdmannFreunde/euf_contact#2]
Beim einfügen eines Bilder werden die Metadaten nicht übernommern.
Dadurch ergibt sich html code ohne diese Infos:

`<img src="files/static/oepr_logo_250_234.svg" alt="" itemprop="image">`

In Zeiten von SEO und Barrierefreiheit sollten diese jedoch befüllt sein.

Danke dir

**Comment by denniserdmann** [comment]
fixed in 1.0.4
